import p5 from "p5";
import { confettiSystem } from "./circle/confetti";
import { roundabout } from "./circle/roundabout";
import { angleBetweenSketch } from "./curve/angle.between";
import { curve } from "./curve/curve";
import { wave } from "./curve/wave";
import { lineIntersect } from "./intersection/line-intersect";
import { segmentIntersect } from "./intersection/segment-intersect";
import { particleSystem } from "./particle-pool/particle-system";
import { angularMotion } from "./physics/angular-motion";
import { physicsSketch2 } from "./physics/physics2";
import { spring } from "./physics/spring";
import { fleeBehavior } from "./steering/flee";
import { pathFollowing } from "./steering/path.following";
import { stayAround } from "./steering/stay-around";
import { steering } from "./steering/steering";
import { triangleSketch } from "./triangles/triangles";

const container = document.createElement("div");
container.classList.add("container");
document.body.append(container);

// new p5(triangleSketch, container);
// new p5(physicsSketch);
// new p5(physicsSketch2, container);
// new p5(angularMotion, container);
// new p5(roundabout, container);
// new p5(spring, container);
// new p5(particleSystem, container);
// new p5(confettiSystem, container);
// new p5(steering, container);
// new p5(fleeBehavior, container);
new p5(stayAround, container);
// new p5(angleBetweenSketch, container);
// new p5(pathFollowing, container);
// new p5(lineIntersect, container);
// new p5(segmentIntersect, container);
// new p5(wave, container);
// new p5(curve);
